# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-10 16:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [(b'zombies', '0001_initial'), (b'zombies', '0002_auto_20160310_1458'), (b'zombies', '0003_auto_20160310_1632')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zombie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField()),
                ('date_of_rebirth', models.DateField(default=datetime.date(2016, 1, 1))),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars')),
                ('bio', models.TextField()),
            ],
        ),
    ]
